=== mpalliser/XML_Formularios/xml/preguntas.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>
    <xs:element name="questions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="question" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="type" type="xs:string"/>
                            <xs:element name="question" type="xs:string"/>
                            <xs:element name="option" type="xs:string"/>
                            <xs:element name="option" type="xs:string"/>
                            <xs:element name="option" type="xs:string"/>
                            <xs:element name="answer" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mpalliser/XML_Formularios/xml/preguntas2.xml
<?xml version="1.0" encoding="UTF-8"?>
<questions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='preguntas.xsd'>
	<question id="quest001">
		<type>select</type>
		<title>¿Que significado tienen las siglas CSS?</title>
		<option>Cascading Style Sheet</option>
		<option>Concatening Style Sheet</option>
		<option>Coworking on Style Sheet</option>
		<answer>0</answer>
	</question>
	<question id="quest002">
		<type>radio</type>
		<title>¿Cual de los siguientes códigos HTML es correcto?</title>
		<option>A) background-image: src='../img/fondo.png';</option>
		<option>B) background: image-url='../img/fondo.png';</option>
		<option>C) background-image: url('../img/fondo.png');</option>
		<answer>2</answer>
	</question>
	<question id="quest003">
		<type>checkbox</type>
		<title>¿Cómo se declara correctamente una variable en JavaScript?</title>
		<option>A) nuevaVariable = true</option>
		<option>B) public boolean nuevaVariable = true;</option>
		<option>C) var nuevaVariable = true;</option>
		<answer>2</answer>
	</question>
	<question id="quest004">
		<type>textarea</type>
		<title>¿Cual es el protocolo de seguridad para las paginas web?</title>
		<answer>HTTPS</answer>
	</question>
	<question id="quest005">
		<type>multiple</type>
		<title>¿Cuales de los siguientes operadores son correctos en JavaScript?</title>
		<option>A) -</option>
		<option>B) *+</option>
		<option>C) ÷</option>
		<option>D) %</option>
		<option>E) ++</option>
		<answer>0</answer>
		<answer>3</answer>
		<answer>4</answer>
	</question>
	<question id="quest006">
		<type>radio</type>
		<title>Si el valor de la variable "numero" es 10,¿Qué mensaje de alerta se mostrará en la pantalla?</title>
		<option>A) "Hola"</option>
		<option>B) "Adiós"</option>
		<option>C) No se mostrará nada</option>
		<answer>1</answer>
	</question>
	<question id="quest007">
		<type>multiple</type>
		<title>¿De que modos podemos incluir colores en el css?</title>
		<option>A) Binario</option>
		<option>B) Hexadecimal</option>
		<option>C) Numbre del color</option>
		<option>D) Mediante el codigo RGB</option>
		<answer>1</answer>
		<answer>2</answer>
		<answer>3</answer>
	</question>
	<question id="quest008">
		<type>textarea</type>
		<title>Escribe el parametro permite poner un identificador en html con el nombre "etiqueta"</title>
		<answer>id="etiqueta"</answer>
	</question>
	<question id="quest009">
		<type>checkbox</type>
		<title>¿Cómo se declara que el ancho de un div sera el 100% en css?</title>
		<option>A) height: 50%;</option>
		<option>B) width: 500px;</option>
		<option>C) width: 100%;</option>
		<option>D) anchura: 100%;</option>
		<answer>2</answer>
		</question>
	<question id="quest010">
		<type>select</type>
		<title>¿Cual de estas NO es una propiedad de posición en CSS?</title>
		<option>A) static</option>
		<option>B) relative</option>
		<option>C) fixed</option>
		<option>D) floating</option>
		<option>E) absolute</option>
		<answer>3</answer>
	</question>
</questions>
